default_events:
  # Core PR lifecycle & review events
  - pull_request
  - pull_request_review
  # Inline review comments (created/edited/deleted)
  - pull_request_review_comment
  # Issue comments on PR "issues" (created/edited/deleted)
  - issue_comment
  # CI / status visibility
  - check_run
  - check_suite
  - status

default_permissions:
  pull_requests: read      # PR details & requested reviewers
  checks: read             # check runs
  statuses: read           # legacy status API
  issues: read             # receive issue_comment events on PRs
  metadata: read           # repo metadata

name: PR Messaging Bot
description: Mirror GitHub Pull Request state into a single Slack message + thread with reviewers and CI check breakdown.
public: false